# Generated by Django 3.0.4 on 2020-04-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='duration',
            field=models.CharField(default='January 2019- Jan 2020', max_length=100),
            preserve_default=False,
        ),
    ]
