# Generated by Django 3.0.4 on 2020-04-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200417_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
